### ISSUE TITLE
部署之后初始密码是多少

### ISSUE THREAD

**Issue by ixxmu** [Colin-XKL/FeedCraft#76]
如题，部署之后没有密码提示？

看起来非常fancy的项目，大模型之后融合RSS真正落地好用的不多，期待佬的继续迭代！

里面有检测软文的receipt，是不是也可以让用户自定义一个类型的，好吧 没密码还没登录，可能已经有了。

**Comment by Colin-XKL** [comment]
> 如题，部署之后没有密码提示？
> 
> 看起来非常fancy的项目，大模型之后融合RSS真正落地好用的不多，期待佬的继续迭代！
> 
> 里面有检测软文的receipt，是不是也可以让用户自定义一个类型的，好吧 没密码还没登录，可能已经有了。



感谢认可

默认的控制台账号为`admin`, 密码为 `adminadmin`. 之前写到Wiki了, 我稍后把这个放到README显眼的地方

对于使用AI检测广告软文的这个功能, 是可以自定义prompt来实现自定义的需求的. 你可以在控制台 新建一个新的craft atom , template 选择 ignore-ad, 然后修改默认的prompt 就可以了. 主要要注意符合条件的文章是要让AI输出true 还是false, 不要搞反了就行, 可以参考原有的prompt
